<?php
$title = 'Wijzig objecttype';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'objecttype',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);

?>
<div class=row">
    <div class="well well-sm">
        <div class="row">
            <div class="col-xs-2"><?php echo $this->formLabel($form->get('name')); ?></div>
            <div class="col-xs-4">
                <?php echo $this->FormElementWw($form->get('name'), $form->getInputFilter()->get('name')); ?>
                <?php echo $this->formElementErrors($form->get('name')); ?>
            </div>
        </div>
        <?php
        if (!$this->is_xmlhttprequest):
        ?>
        <div class="pull-left">
            <button class='btn btn-success'><span class='glyphicon glyphicon-ok'></span> Opslaan</button>
            <a href="/objecttype/view/<?php echo $this->id; ?>" class='btn btn-inverse' onClick='document.location.href = "/objecttype/view/<?php echo $this->id; ?>; return false;"'><span class='glyphicon glyphicon-remove'></span> Annuleer</a>
        </div>
        <?php
        endif;
        ?>
        <div class="clearfix"></div>
        <?php echo $this->form()->closeTag($form); ?>
    </div>
</div>
<?php
