<?php
$title = 'Objecttypes';
$this->headTitle($title);
?>
<h1><span class="glyphicon glyphicon-tags"></span> <?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class="btn btn-xs btn-success" href="<?php echo $this->url('objecttype', array('controller'=>'objecttype','action'=>'add'));?>">
        <span class="glyphicon glyphicon-plus"></span> Toevoegen nieuw objecttype
    </a>
</p>

<table class="table">
<tr>
    <th>ID</th>
    <th>Naam</th>
    <th>Acties</th>
</tr>
<?php foreach ($objecttypes as $objecttype) : ?>
<tr>
    <td><?php echo $objecttype->getId();?></td>
    <td><?php echo $this->escapeHtml($objecttype->getName());?></td>
    <td>
        <a class="btn btn-primary btn-xs" href="<?php echo $this->url('objecttype',
            array('action'=>'view', 'id' => $objecttype->getId()));?>"><span class="glyphicon glyphicon-eye-open"></span> Bekijk</a>
    </td>
</tr>
<?php endforeach; ?>
</table>