<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Facturen'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Scripts -->
        <?php

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/assets/css/datatables-bootstrap.css')
                ->prependStylesheet($this->basePath() . '/assets/css/datepicker.css')
                ->prependStylesheet($this->basePath() . '/assets/css/searchform.css')
                ->prependStylesheet($this->basePath() . '/assets/css/default.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/overcast/jquery-ui-1.10.3.custom.css')
            ;

            echo $this->headScript()
                ->prependFile($this->basePath() . '/assets/js/datatables-bootstrap.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.dataTables.1.9.4.js')
                ->prependFile($this->basePath() . '/assets/js/hogan-2.0.0.js')
                ->prependFile($this->basePath() . '/assets/js/typeahead.min.js')
                ->prependFile($this->basePath() . '/assets/js/chosen.jquery.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap-datepicker.js')
                ->prependFile($this->basePath() . '/assets/js/bootbox.min.js')
                ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.bootstrap.min.js')
                ->prependFile($this->basePath() . '/assets/js/jquery.js')
                ->prependFile($this->basePath() . '/assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/assets/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top">
            <div class="container">

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a class="brand" href="<?php echo $this->url('home') ?>"><i class="glyphicon glyphicon-home"></i> <?php echo $this->translate('Home') ?></a></li>

                        <li class="">
                            <a href="<?php echo $this->url('owner') ?>"><i class="glyphicon glyphicon-user"></i> <?php echo $this->translate('Eigenaren') ?></a>
                        </li>
                        <li class="">
                            <a href="<?php echo $this->url('winter') ?>"><i class="glyphicon glyphicon-asterisk"></i> <?php echo $this->translate('Winterstallers') ?></a>
                        </li>
                        <li class="">
                            <a href="<?php echo $this->url('objecttype') ?>"><i class="glyphicon glyphicon-tags"></i> <?php echo $this->translate('Objecttypes') ?></a>
                        </li>
                        <li class="">
                            <a href="<?php echo $this->url('invoice') ?>"><i class="glyphicon glyphicon-list"></i> <?php echo $this->translate('Facturen') ?></a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-wrench"></span> <?php echo $this->Translate('Instellingen');?>&nbsp;<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="<?php echo $this->url('user'); ?>"><span class="glyphicon glyphicon-user"></span> <?php echo $this->Translate('Gebruikers'); ?></a></li>
                                </ul>
                            </li>

                        <li>
                            <a data-logout-action="<?php echo $this->url('logout'); ?>" data-logout-message="Weet u zeker dat u wilt uitloggen?" rel=\"tooltip\" title="Uitloggen" href="#" id="logoutLink">
                                <span class="glyphicon glyphicon-lock"></span>
                                <?php echo $this->translate('Uitloggen'); ?> (<?php if ($this->zfcUserIdentity()) { echo $this->escapeHtml($this->zfcUserIdentity()->getDisplayname()); } ?>)
                            </a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>

            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <div id="dialog" title="Titel"></div>
        <script>
        $(document).ready(function() {
            $(document).on('click', '#logoutLink', function(event) {
                $this = $(this);

                var logoutMessage = $this.data("logoutMessage");
                var action = $this.data("logoutAction");

                bootbox.confirm(logoutMessage, function (result) {
                    if (result) {
                        $.ajax({
                            type: "POST",
                            url: action,
                            success: function (html) {
                                window.location.href = "<?php echo $this->url('owner'); ?>";
                            }
                        });
                    }
                });
            });
        });
        </script>
    </body>
</html>
