<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Henri de Jong">
        <link rel="shortcut icon" href="<?php echo $this->basePath(); ?>/assets/ico/favicon.png">

        <?php echo $this->headTitle('Facturen')->setSeparator(' - ') ?>

        <?php
            echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/assets/css/login.css')
                ->prependStylesheet($this->basePath() . '/assets/css/bootstrap.min.css')
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/assets/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/assets/js/jquery.js')
            ->prependFile($this->basePath() . '/assets/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/assets/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>

    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>