<?php

namespace Application\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-08 at 20:12:14.
 */
class ObjectTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Object;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers Application\Entity\Object::getId
     */
    public function testGetId()
    {
        $id = 1;
        $this->assertNull($this->object->getId());
        $this->object->setId($id);
        $this->assertEquals($id, $this->object->getId());
    }

    /**
     * @covers Application\Entity\Object::setId
     */
    public function testSetId()
    {
        $this->assertEquals($this->object, $this->object->setId(1));
    }

    /**
     * @covers Application\Entity\Object::getName
     */
    public function testGetName()
    {
        $name = 'Objectnaam';
        $this->assertNull($this->object->getName());
        $this->object->setName($name);
        $this->assertEquals($name, $this->object->getName());
    }

    /**
     * @covers Application\Entity\Object::setName
     */
    public function testSetName()
    {
        $this->assertEquals($this->object, $this->object->setName('Objectnaam'));
    }

    /**
     * @covers Application\Entity\Object::getType
     * @todo   Implement testGetType().
     */
    public function testGetType()
    {
        $objecttype = new \Application\Entity\Objecttype;
        $this->assertNull($this->object->getType());
        $this->object->setType($objecttype);
        $this->assertEquals($objecttype, $this->object->getType());
    }

    /**
     * @covers Application\Entity\Object::setType
     */
    public function testSetType()
    {
        $this->assertEquals($this->object, $this->object->setType(new \Application\Entity\Objecttype));
    }

    /**
     * @covers Application\Entity\Object::exchangeArray
     * @todo   Implement testExchangeArray().
     */
    public function testExchangeArray() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Entity\Object::getArrayCopy
     * @todo   Implement testGetArrayCopy().
     */
    public function testGetArrayCopy() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Entity\Object::setInputFilter
     * @todo   Implement testSetInputFilter().
     */
    public function testSetInputFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Application\Entity\Object::getInputFilter
     * @todo   Implement testGetInputFilter().
     */
    public function testGetInputFilter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
