Sehr geehrter <?php echo $salutation . ' ' . $invoice->getOwner()->getInitials() . ' ' . $invoice->getOwner()->getName() . ',' ?>


In Beilage die Rechnung Ihres Servicebetrag 2014 mit Stromverbrauch 2013
über 10 Kwh.
Wir bitten Sie, den Betrag innerhalb von 14 Tagen auf das Konto
xx.xx.xx.xxx der ABN-AMRO Bank, auf den Namen von 'Vereinigung'
mit der Angabe Ihrer Liegeplatznummer zu überweisen.

IBAN: NL12 BANK XX XXXX XXXX
BIC: ABNANL2A


Mit Freundlichen  Grüssen,

Schatzmeister
