Geachte <?php echo $salutation . ' ' . $invoice->getOwner()->getInitials() . ' ' . $invoice->getOwner()->getName() . ',' ?>


Hierbij ontvangt u uw factuur voor de servicekosten 2014, alsmede de afrekening van elektriciteitsverbruik april 2013 - maart 2014.

Ik verzoek u het totaalbedrag binnen 14 dagen over te maken op rekeningnummer:
IBAN : NL12 ABNA XX XXXX XXXX
BIC:  ABNA NL2A

Met vriendelijke groet,

Penningmeester
