<div class="hero-unit">
    <h1><?php echo sprintf($this->translate('Wellewille %sFactureren%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Eigenaren') ?></h2>
        <p><?php echo sprintf($this->translate('Bekijk, wijzig en voeg eigenaren toe. ')) ?></p>
        <p><a class="btn btn-success" href="./owner" target="_blank"><?php echo $this->translate('Eigenaren') ?> &raquo;</a></p>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Winterstallers') ?></h2>
        <p><?php echo sprintf($this->translate('Bekijk, wijzig en voeg winterstallers toe. ')) ?></p>
        <p><a class="btn btn-success" href="./winter" target="_blank"><?php echo $this->translate('Winterstallers') ?> &raquo;</a></p>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Statistieken') ?></h2>
        <p><?php echo sprintf($this->translate('Bekijk statistieken. ')) ?></p>
       <p><a class="btn btn-success" href="./stats" target="_blank"><?php echo $this->translate('Statistieken') ?> &raquo;</a></p>
   </div>
</div>
