<div class=" col-md-4 col-md-offset-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Inloggen</h2>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class=" col-md-12">
                    <img width="100%" src="<?php echo $this->basePath(); ?>/img/logo.png">
                </div>
            </div>
            <div class="row"><br></div>
            <div class="col-md-12">
                <form action="<?php $this->Url('login'); ?>" method="post" class="form-horizontal">
                    <div class="form-group">
                        <input name="identity" class="form-control" placeholder="Gebruikersnaam" id="emailaddress" value="" type="text">
                    </div>
                    <div class="form-group">
                        <input name="credential" class="form-control" placeholder="Wachtwoord" id="password" value="" type="password">
                    </div>
                    <div class="form-group">
                        <input name="submit" id="submitbutton" class="btn btn-lg btn-primary btn-block" value="Login" type="submit">
                    </div>
                </form>
                <?php
                    echo $this->FlashMessenger()
                        ->setMessageOpenFormat('<div class="alert alert-danger">')
                        ->setMessageSeparatorString('</div><div class="alert alert-danger">')
                        ->setMessageCloseString('</div>')
                        ->render('zfcuser-login-form');
                ?>
            </div>
        </div>
    </div>
</div>
