<?php

$title = 'Toevoegen Eigenaar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('owner', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
//echo $this->formHidden($form->get('id'));
//echo $this->formRow($form->get('name'));
//echo $this->formRow($form->get('gender'));
//echo $this->formRow($form->get('street'));
//echo $this->formRow($form->get('housenumber'));
//echo $this->formRow($form->get('postalcode'));
//echo $this->formRow($form->get('city'));
//echo $this->formRow($form->get('country'));
//
//echo $this->formSubmit($form->get('submit'));
echo $this->formCollection($form);

echo $this->form()->closeTag();