<?php

$title = 'Verwijder eigenaar';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Weet je zeker dat je 
    '<?php echo $this->escapeHtml($owner->getName()); ?>'
    wilt verwijderne?
</p>
<?php
$url = $this->url('owner', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $owner->getId(); ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>